<?php


return [

    'smsapi'=>env('SMS_API'),
    'LIVE-TICKET'=>env('LIVE_TICKET_CONNECTION'),
    'TEST-TICKET'=>env('TEST_TICKET_CONNECTION'),
    'TEST-TICKET-WEB-PORTAL'=>env('TEST_TICKET_CONNECTION_WEB_PORTAL'),
    'LIVE-TICKET-WEB-PORTAL'=>env('LIVE_TICKET_CONNECTION_WEB_PORTAL'),
    'TPESA_DISBURSEMENT_API'=>env('TPESA_DISBURSEMENT_API'),
    'TPESA_TEST_DISBURSEMENT_API'=>env('TPESA_TEST_DISBURSEMENT_API'),
    'TPESA_SECRETE_KEY'=>env('TPESA_SECRETE_KEY'),
    'TEMESA_ACCOUNT'=>env('TEMESA_ACCOUNT'),
    'TPESA_AGENT_TOP_UP_API'=>env('TPESA_AGENT_TOP_UP_API'),
    'TEST_TPESA_AGENT_TOP_UP_API'=>env('TEST_TPESA_AGENT_TOP_UP_API'),
    'TEST_TPESA_NCARD_DISBURSEMENT_BALANCE_API'=>env('TEST_TPESA_NCARD_DISBURSEMENT_BALANCE_API'),
    'TEST_TPESA_AGGREGATOR_TOP_UP_API'=>env('TEST_TPESA_AGGREGATOR_TOP_UP_API'),
    'TEST_TPESA_CUSTOMER_TX_API'=>env('TEST_TPESA_CUSTOMER_TX_API'),
    'TEST_WITH_DRAW_API'=>env('TEST_WITH_DRAW_API'),
    'LIVE_JASPER_SERVER'=>env('LIVE_JASPER_SERVER'),
    'TEST_JASPER_SERVER'=>env('TEST_JASPER_SERVER'),
    'API2_URL'=>env('API2_URL'),
    'HOST'=>env('HOST'),
    'X_API_KEY' =>env('X_API_KEY'),
    'X_USER'=>env('X_USER'),
    'API_DATA_SYNC_TPESA_URL'=>env('API_DATA_SYNC_TPESA_URL')


];
